version: "3"
services:
  front:
    container_name: "baro_factory"
    build:
      context: ../
      dockerfile: local/Dockerfile
    ports:
      - "4030:3000"
    restart: always
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ../resource:/resource
      - /resource/node_modules
      - /resource/.next
    stdin_open: true
    tty: true
